inherit_gem:
    rubocop-shopify: rubocop.yml
require: rubocop-rspec
require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.7

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/MethodCallWithArgsParentheses:
  Enabled: false
