plugins:
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Style/DateTime:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/ClassMethodsDefinitions:
  Enabled: true
  EnforcedStyle: def_self

Layout/LineLength:
  Enabled: true
  Max: 120
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_first_argument

Naming/InclusiveLanguage:
  Enabled: false

Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be a Fixnum or
  # a Float.
  Enabled: false
  Max: 50

Metrics/BlockNesting:
  Enabled: false
  Max: 3

Metrics/BlockLength:
  Enabled: false
  Max: 25

Metrics/ClassLength:
  Enabled: false
  CountComments: false  # count full line comments?
  Max: 100

Metrics/ModuleLength:
  Enabled: false
  CountComments: false  # count full line comments?
  Max: 100

Metrics/MethodLength:
  Enabled: false
  CountComments: false  # count full line comments?
  Max: 10

# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Enabled: false
  Max: 20

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Enabled: false
  Max: 8

Layout/MultilineOperationIndentation:
  EnforcedStyle: aligned

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
  SupportedStyles:
    - aligned
    - indented
    - indented_relative_to_receiver
  # By default, the indentation width from Style/IndentationWidth is used
  # But it can be overridden by setting this parameter
  IndentationWidth: ~

# Though the style guides recommend against them, I like perl back references.
# They are much more concise than the recommended: $2 vs. Regexp.last_match(2).
# Two characters versus 18!
# Cop supports --auto-correct.
Style/PerlBackrefs:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ProceduralMethods, FunctionalMethods, IgnoredMethods.
# SupportedStyles: line_count_based, semantic, braces_for_chaining
# ProceduralMethods: benchmark, bm, bmbm, create, each_with_object, measure, new, realtime, tap, with_object
# FunctionalMethods: let, let!, subject, watch
# IgnoredMethods: lambda, proc, it
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
  ProceduralMethods: expect

# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment, ForceEqualSignAlignment.
Layout/ExtraSpacing:
  AllowForAlignment: true

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: format, sprintf, percent
Style/FormatString:
  Enabled: false

# Configuration parameters: NamePrefix, NamePrefixBlacklist, NameWhitelist.
# NamePrefix: is_, has_, have_
# NamePrefixBlacklist: is_, has_, have_
# NameWhitelist: is_a?
Naming/PredicateName:
  AllowedMethods: has_overlaps_within?
  Exclude:
    - 'spec/**/*'

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: always, never
Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: always

# I like using !! to convert a value to boolean.
Style/DoubleNegation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5
