* Labrat

A linux command-line command for printing labels.

** Motivation

I need to print labels, and in my case, mostly file folder labels.  I
typically want to print to a Dymo LabelWriter, of which I own several
variants.  The problem is that I work almost entirely in Linux, but the simple
task of printing file folder labels has required opening a GUI application,
such as the very fine glabels, or worse, switching to a Windows or Mac to run
Dymo's proprietary GUI.  The Dymo GUI is particularly irksome because it takes
a long time to start up and demands that you register every time you open it.

I longed for a way to just print a file label from the command line, and even
better, from within my editor, Emacs.  After giving up looking for such a
thing without success, I decided to write my own.  Hence labrat.  With it,
printing a file folder label is as simple as:

#+begin_src sh
  $ labrat 'First Line of Label++And the Second Line'
  #+end_src

After proper configuration, the



Welcome to your new gem! In this directory, you'll find the files you need to
be able to package up your Ruby library into a gem. Put your Ruby code in the
file `lib/labrat`. To experiment with that code, run `bin/console` for an
interactive prompt.

TODO: Delete this and the text above, and describe your gem

** Installation

Add this line to your application's Gemfile:

#+begin_SRC sh
  $ gem install labrat
#+end_SRC

** Usage

TODO: Write usage instructions here

* Development

After checking out the repo, run `bin/setup` to install dependencies. Then,
run `rake spec` to run the tests. You can also run `bin/console` for an
interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake
install`. To release a new version, update the version number in `version.rb`,
and then run `bundle exec rake release`, which will create a git tag for the
version, push git commits and the created tag, and push the `.gem` file to
[rubygems.org](https://rubygems.org).

* Contributing

Bug reports and pull requests are welcome on GitHub at
https://github.com/ddoherty03/labrat.
